const region = [
  {
    siDoName: "서울",
    siDoFull: "서울특별시",
    siDo: 11,
    guGuns: [
      { guGunName: "강남구", guGun: 680 },
      { guGunName: "강동구", guGun: 740 },
      { guGunName: "강북구", guGun: 305 },
      { guGunName: "강서구", guGun: 500 },
      { guGunName: "관악구", guGun: 620 },
      { guGunName: "광진구", guGun: 215 },
      { guGunName: "구로구", guGun: 530 },
      { guGunName: "금천구", guGun: 545 },
      { guGunName: "노원구", guGun: 350 },
      { guGunName: "도봉구", guGun: 320 },
      { guGunName: "동대문구", guGun: 230 },
      { guGunName: "동작구", guGun: 590 },
      { guGunName: "마포구", guGun: 440 },
      { guGunName: "서대문구", guGun: 410 },
      { guGunName: "서초구", guGun: 650 },
      { guGunName: "성동구", guGun: 200 },
      { guGunName: "성북구", guGun: 290 },
      { guGunName: "송파구", guGun: 710 },
      { guGunName: "양천구", guGun: 470 },
      { guGunName: "영등포구", guGun: 560 },
      { guGunName: "용산구", guGun: 170 },
      { guGunName: "은평구", guGun: 380 },
      { guGunName: "종로구", guGun: 110 },
      { guGunName: "중구", guGun: 140 },
      { guGunName: "중랑구", guGun: 260 },
    ],
  },
  {
    siDoName: "부산",
    siDoFull: "부산광역시",
    siDo: 26,
    guGuns: [
      { guGunName: "강서구", guGun: 440 },
      { guGunName: "금정구", guGun: 410 },
      { guGunName: "기장군", guGun: 710 },
      { guGunName: "남구", guGun: 290 },
      { guGunName: "동구", guGun: 170 },
      { guGunName: "동래구", guGun: 260 },
      { guGunName: "부산진구", guGun: 230 },
      { guGunName: "북구", guGun: 320 },
      { guGunName: "사상구", guGun: 530 },
      { guGunName: "사하구", guGun: 380 },
      { guGunName: "서구", guGun: 140 },
      { guGunName: "수영구", guGun: 500 },
      { guGunName: "연제구", guGun: 470 },
      { guGunName: "영도구", guGun: 200 },
      { guGunName: "중구", guGun: 110 },
      { guGunName: "해운대구", guGun: 350 },
    ],
  },
  {
    siDoName: "대구",
    siDoFull: "대구광역시",
    siDo: 27,
    guGuns: [
      { guGunName: "남구", guGun: 200 },
      { guGunName: "달서구", guGun: 290 },
      { guGunName: "달성군", guGun: 710 },
      { guGunName: "동구", guGun: 140 },
      { guGunName: "북구", guGun: 230 },
      { guGunName: "서구", guGun: 170 },
      { guGunName: "수성구", guGun: 260 },
      { guGunName: "중구", guGun: 110 },
    ],
  },
  {
    siDoName: "인천",
    siDoFull: "인천광역시",
    siDo: 28,
    guGuns: [
      { guGunName: "강화군", guGun: 710 },
      { guGunName: "계양구", guGun: 245 },
      { guGunName: "남구", guGun: 170 },
      { guGunName: "남동구", guGun: 200 },
      { guGunName: "동구", guGun: 140 },
      { guGunName: "부평구", guGun: 237 },
      { guGunName: "서구", guGun: 260 },
      { guGunName: "연수구", guGun: 185 },
      { guGunName: "옹진군", guGun: 720 },
      { guGunName: "중구", guGun: 110 },
    ],
  },
  {
    siDoName: "광주",
    siDoFull: "광주광역시",
    siDo: 29,
    guGuns: [
      { guGunName: "광산구", guGun: 200 },
      { guGunName: "남구", guGun: 115 },
      { guGunName: "동구", guGun: 110 },
      { guGunName: "북구", guGun: 170 },
      { guGunName: "서구", guGun: 140 },
    ],
  },
  {
    siDoName: "대전",
    siDoFull: "대전광역시",
    siDo: 30,
    guGuns: [
      { guGunName: "대덕구", guGun: 230 },
      { guGunName: "동구", guGun: 110 },
      { guGunName: "서구", guGun: 170 },
      { guGunName: "유성구", guGun: 200 },
      { guGunName: "중구", guGun: 140 },
    ],
  },
  {
    siDoName: "울산",
    siDoFull: "울산광역시",
    siDo: 31,
    guGuns: [
      { guGunName: "남구", guGun: 140 },
      { guGunName: "동구", guGun: 170 },
      { guGunName: "북구", guGun: 200 },
      { guGunName: "울주군", guGun: 710 },
      { guGunName: "중구", guGun: 110 },
    ],
  },
  {
    siDoName: "세종",
    siDoFull: "세종특별자치시",
    siDo: 36,
    guGuns: [{ guGunName: "세종특별자치시", guGun: 110 }],
  },
  {
    siDoName: "경기도",
    siDoFull: "경기도",
    siDo: 41,
    guGuns: [
      { guGunName: "가평군", guGun: 820 },
      { guGunName: "고양시 덕양구", guGun: 281 },
      { guGunName: "고양시 일산구", guGun: 283 },
      { guGunName: "고양시 일산동구", guGun: 285 },
      { guGunName: "고양시 일산서구", guGun: 287 },
      { guGunName: "과천시", guGun: 290 },
      { guGunName: "광명시", guGun: 210 },
      { guGunName: "광주시", guGun: 610 },
      { guGunName: "구리시", guGun: 310 },
      { guGunName: "군포시", guGun: 410 },
      { guGunName: "김포시", guGun: 570 },
      { guGunName: "남양주시", guGun: 360 },
      { guGunName: "동두천시", guGun: 250 },
      { guGunName: "부천시 소사구", guGun: 197 },
      { guGunName: "부천시 오정구", guGun: 199 },
      { guGunName: "부천시 원미구", guGun: 195 },
      { guGunName: "성남시 분당구", guGun: 135 },
      { guGunName: "성남시 수정구", guGun: 131 },
      { guGunName: "성남시 중원구", guGun: 133 },
      { guGunName: "수원시 권선구", guGun: 113 },
      { guGunName: "수원시 영통구", guGun: 117 },
    ],
  },
];

export default region;
